movies/urls.py
from django.urls import path
from movies import views

app_name = 'movies'

urlpatterns = [
        path('', views.index, name='index'),
        path('/gráficos', views.graphics, name='graphics'),


]

project/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('movies.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

movies/models.py
from django.db import models

# Create your models here.

movies/views.py
from django.shortcuts import render

# Create your views here.
def index(request): return render(request, 'movies/index.html')

def graphics(request): return render(request, 'movies/graphics.html')

movies/templates/base_templates/global/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    {% include "base_templates/global/partials/_head.html" %}
</head>
<body>

    {% include "base_templates/global/partials/_header.html" %}


    

    <main class="content">
        {% block content %}{% endblock content %}

    </main>

    
</body>
</html>

movies/templates/base_templates/global/partials/_head.html
{% load static %}
<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cine Data</title>
    <link rel="stylesheet" href="{% static 'global/css/style.css' %}">

movies/templates/base_templates/global/partials/_header.html
<header style=" padding: none; margin: none !important" >
  <div style="display: grid; justify-items: center;     ">
    <h1 class="teste">
      <a
        style="text-decoration: none; list-style: none; color: inherit"
        href="{% url 'movies:index' %}"
      >
        Cine Data
      </a>
    </h1>
  </div>
  <nav style="display: grid; grid-template-columns: 1fr 1fr; justify-content:center; margin: 0 40% 0 40%;">
    <div style="border: solid 1px black; text-align: center;" >
      <a href="{% url 'movies:index' %}">Cadastro</a> 
    </div>
    <div style="border: solid 1px black; text-align: center;"> <a href="{% url 'movies:graphics' %}">Gráficos</a> </div>
  </nav>
</header>
<style>
  
</style>

movies/templates/movies/graphics.html
{% extends "base_templates/global/base.html" %}{% block content %}
<div style="display: grid; justify-items: center; justify-self: center">
    Gráficos
</div>
{% endblock content %}

movies/templates/movies/index.html
{% extends "base_templates/global/base.html" %}{% block content %}
<div style="display: grid; justify-items: center; justify-self: center; padding: 80px;">
    Cadastro
</div>
{% endblock content %}